workflows:
  version: 2
  test-release:
    jobs:
      - lint
      - test
      - test-mysql
      - test-postgres
      - test-redis
      - test-kafka
      - release:
          requires:
            - lint
            - test
            - test-mysql
            - test-postgres
            - test-redis
            - test-kafka

version: 2
jobs:
  lint:
    docker:
      - image: circleci/golang:1.14

    working_directory: /go/src/github.com/cube2222/octosql
    steps:
      - run: go get github.com/burntsushi/go-sumtype
      - checkout
      - run: GO111MODULE=on go mod vendor
      - run: go-sumtype ./...

  test:
    docker:
      - image: circleci/golang:1.14
    environment:
      GO111MODULE: "on"

    working_directory: /go/src/github.com/cube2222/octosql
    steps:
      - checkout

      - run: go test -v
      - run: go test -v ./cmd/...
      - run: go test -v ./config/...
      - run: go test -v ./datasources/json/...
      - run: go test -v ./datasources/csv/...
      - run: go test -v ./datasources/excel/...
      - run: go test -v ./datasources/parquet/...
      - run: go test -v ./execution/...
      - run: go test -v ./logical/...
      - run: go test -v ./parser/...
      - run: go test -v ./physical/...
      - run: go test -v ./storage/...

  test-mysql:
    docker:
      - image: circleci/golang:1.14
        environment:
          GO111MODULE: "on"
      - image: circleci/mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: toor
          MYSQL_DATABASE: mydb

    working_directory: /go/src/github.com/cube2222/octosql
    steps:
      - checkout

      - run: sleep 4
      - run: go test -v ./datasources/sql/mysql...

  test-postgres:
    docker:
      - image: circleci/golang:1.14
        environment:
          GO111MODULE: "on"
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: toor
          POSTGRES_DB: mydb

    working_directory: /go/src/github.com/cube2222/octosql
    steps:
      - checkout

      - run: go test -v ./datasources/sql/postgres...

  test-redis:
    docker:
      - image: circleci/golang:1.14
        environment:
          GO111MODULE: "on"
      - image: circleci/redis:latest

    working_directory: /go/src/github.com/cube2222/octosql
    steps:
      - checkout

      - run: go test -v ./datasources/redis/...

  test-kafka:
    docker:
      - image: circleci/golang:1.14
        environment:
          GO111MODULE: "on"
      - image: spotify/kafka:latest

    working_directory: /go/src/github.com/cube2222/octosql
    steps:
      - checkout

      - run: go test -v ./datasources/kafka/...

  release:
    docker:
      - image: circleci/golang:1.14
    environment:
      GO111MODULE: "on"

    steps:
      - run: go get -u -v github.com/cube2222/octosql/cmd/octosql@${CIRCLE_SHA1}
      - run: GOOS=windows go get -u -v github.com/cube2222/octosql/cmd/octosql@${CIRCLE_SHA1}
      - run: GOOS=darwin go get -u -v github.com/cube2222/octosql/cmd/octosql@${CIRCLE_SHA1}

      - store_artifacts:
          path: "/go/bin"